## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [35]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [33]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Развернуть вектор (первый становится последним)

In [34]:
v[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [32]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [31]:
np.nonzero([1, 2, 0, 0, 4, 0])[0]

array([0, 1, 4])

Создать 3x3 единичную матрицу

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [24]:
np.random.random((3, 3, 3)) * 100

array([[[10.73709638, 13.78696806, 98.84834796],
        [34.86037609, 15.03844092,  0.83060509],
        [28.14281863, 79.46781567, 63.04848089]],

       [[24.77296177, 93.71807005,  9.24400906],
        [27.61283877,  7.73064014, 85.87059824],
        [62.28635578, 51.40237054, 38.81758704]],

       [[23.40470707, 55.14757329, 67.0463596 ],
        [26.87483895, 66.81323179, 21.1892175 ],
        [58.68466071, 78.5983801 , 88.09493696]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [39]:
np.random.random(30).mean()

0.4488355480190385

Перемножить матрицы 5x3 и 3x2

In [27]:
m1 = np.random.random((5, 3)) * 100
m2 = np.random.random((3, 2))
m1.dot(m2)

array([[ 77.08899793,  13.18146501],
       [156.12008325,  33.03908746],
       [ 63.92734776,  22.6114826 ],
       [111.65592796,  17.49732822],
       [ 44.2389717 ,  14.24966649]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [41]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [42]:
m = np.random.random(30)
m[m.argmax()] = 0
print(m)

[0.10151585 0.91626175 0.69797156 0.45375951 0.72778564 0.66914751
 0.04339937 0.05210761 0.95195178 0.98715893 0.18384402 0.
 0.53348637 0.07268879 0.87340737 0.76316785 0.68496269 0.8990192
 0.36300479 0.52477124 0.88778274 0.85297538 0.73951829 0.16470799
 0.14205226 0.24261898 0.38527344 0.71863577 0.11762149 0.30904145]


Преобразовать массив из float в int

In [49]:
m.astype(np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [50]:
import scipy.spatial

m = np.random.random((10, 2))
scipy.spatial.distance.cdist(m, m)

array([[0.        , 0.91822594, 0.59197294, 0.19014183, 0.69520077,
        0.52887081, 0.6496702 , 0.2254342 , 0.12846289, 0.39786301],
       [0.91822594, 0.        , 0.34413858, 0.82530158, 0.29250046,
        0.39494961, 0.4055899 , 0.89689919, 0.94753086, 0.54824572],
       [0.59197294, 0.34413858, 0.        , 0.48247629, 0.11788451,
        0.06985739, 0.16357777, 0.61867992, 0.6074893 , 0.28564266],
       [0.19014183, 0.82530158, 0.48247629, 0.        , 0.56783119,
        0.43186926, 0.50038591, 0.3812719 , 0.13209734, 0.38379228],
       [0.69520077, 0.29250046, 0.11788451, 0.56783119, 0.        ,
        0.18735542, 0.11585104, 0.73499621, 0.69745267, 0.40327652],
       [0.52887081, 0.39494961, 0.06985739, 0.43186926, 0.18735542,
        0.        , 0.2132871 , 0.54890346, 0.55259647, 0.2178129 ],
       [0.6496702 , 0.4055899 , 0.16357777, 0.50038591, 0.11585104,
        0.2132871 , 0.        , 0.72442547, 0.63240685, 0.42339442],
       [0.2254342 , 0.89689919, 0.6186799

Случайно расположить p элементов в 2D массив

In [51]:
p = 4
m = np.random.random((2, 10))
m.put(np.random.choice(range(2 * 10), p, replace=False), 100)
print(m)

[[  0.86727117   0.49141937   0.69159561   0.77021077   0.21417971
    0.73308586   0.86983694   0.45485372 100.         100.        ]
 [100.           0.59780317   0.14604221   0.74170075   0.98015114
    0.61429994   0.96679092 100.           0.62068057   0.19306979]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [52]:
m = np.arange(1, 6)
n = 3
z = np.zeros(len(m) + (len(m) - 1) * n)
z[::n + 1] = m
print(z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [53]:
m = np.array([1, 2, 2, 3, 3, 3, 4, 4])
np.bincount(m).argmax()

3

Найти n наибольших значений в массиве

In [54]:
m = np.array([2, 1, 2, 4, 3, 3, 4, 3])
n = 2
m.sort()
print(m[-n:])

[4 4]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

Посмотреть первые 5 записей

Сколько наблюдений в наборе данных?


Сколько столбцов в наборе данных?

Напечатайте все названия столбцов

Какое название у 105 столбца?

Какой тип наблюдений в 105 столбце?

Как проиндексирован набор данных?

Каково значение имени продукта в 19-м наблюдении?

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?